version: '3.8'

services:
  client-service:
    image: client-service
    build:
      context: ./client
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-client:5432/client-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db-client
    networks:
      - default

  account-service:
    image: account-service
    build:
      context: ./account
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-account:5432/account-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db-account
    networks:
      - default

  db-client:
    image: postgres:15.3
    environment:
      POSTGRES_DB: client-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6541:5432"
    networks:
      - default

  db-account:
    image: postgres:15.3
    environment:
      POSTGRES_DB: account-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6540:5432"
    networks:
      - default

networks:
  default:
    driver: bridge
